import os
import json
import traceback
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from pydantic import BaseModel
import uvicorn
from dotenv import load_dotenv

# Load env variables
load_dotenv()

from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.agents.run_config import RunConfig, StreamingMode
from google.adk.models.google_llm import _ResourceExhaustedError
from google.genai import types
from concierge_agent import root_agent
from concierge_agent.context import current_user_id

app = FastAPI(title="Antigravity AI Agent API Server", version="1.0.0")

# Setup CORS for the Vite development server (port 5173)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

session_service = InMemorySessionService()
runner = Runner(
    agent=root_agent,
    app_name="concierge_agent",
    session_service=session_service,
)

class ChatRequest(BaseModel):
    message: str
    user_id: str
    session_id: str

class ChatResponse(BaseModel):
    reply: str
    actions_taken: list[dict] = []
    session_id: str

@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    token = current_user_id.set(request.user_id)
    try:
        content = types.Content(role="user", parts=[types.Part(text=request.message)])
        reply = ""
        actions_taken = []
        
        async for event in runner.run_async(
            user_id=request.user_id,
            session_id=request.session_id,
            new_message=content
        ):
            # Capture tool calls
            calls = event.get_function_calls()
            if calls:
                for call in calls:
                    actions_taken.append({
                        "type": "tool_call",
                        "name": call.name,
                        "args": call.args
                    })
            
            # Capture tool responses
            responses = event.get_function_responses()
            if responses:
                for resp in responses:
                    actions_taken.append({
                        "type": "tool_response",
                        "name": resp.name,
                        "response": resp.response
                    })
            
            # Capture final response
            if event.is_final_response():
                if event.content and event.content.parts:
                    reply = event.content.parts[0].text

        if not reply:
            reply = "No response generated by agent."

        return ChatResponse(
            reply=reply,
            actions_taken=actions_taken,
            session_id=request.session_id
        )
    except _ResourceExhaustedError as e:
        traceback.print_exc()
        return JSONResponse(
            status_code=429,
            content={
                "error": "rate_limited",
                "message": "AI 服务繁忙，请稍后重试",
                "retry_after": 40
            }
        )
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        try:
            current_user_id.reset(token)
        except ValueError:
            pass

@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    token = current_user_id.set(request.user_id)
    
    async def event_generator():
        try:
            content = types.Content(role="user", parts=[types.Part(text=request.message)])
            actions_taken = []
            accumulated_reply = ""
            
            # Configure Runner to output Server-Sent Events (SSE)
            run_config = RunConfig(streaming_mode=StreamingMode.SSE)
            
            async for event in runner.run_async(
                user_id=request.user_id,
                session_id=request.session_id,
                new_message=content,
                run_config=run_config
            ):
                # Capture tool calls
                calls = event.get_function_calls()
                if calls:
                    for call in calls:
                        action = {
                            "type": "tool_call",
                            "name": call.name,
                            "args": call.args
                        }
                        actions_taken.append(action)
                        yield f"data: {json.dumps({'type': 'action', 'action': action})}\n\n"
                
                # Capture tool responses
                responses = event.get_function_responses()
                if responses:
                    for resp in responses:
                        action = {
                            "type": "tool_response",
                            "name": resp.name,
                            "response": resp.response
                        }
                        actions_taken.append(action)
                        yield f"data: {json.dumps({'type': 'action', 'action': action})}\n\n"
                
                # Capture text chunks
                if event.content and event.content.parts:
                    part = event.content.parts[0]
                    if part.text:
                        if event.partial:
                            yield f"data: {json.dumps({'type': 'chunk', 'text': part.text})}\n\n"
                        else:
                            accumulated_reply = part.text
            
            # Yield the final summary event
            yield f"data: {json.dumps({'type': 'final', 'reply': accumulated_reply, 'actions_taken': actions_taken, 'session_id': request.session_id})}\n\n"
        except _ResourceExhaustedError as e:
            yield f"data: {json.dumps({'type': 'error', 'error': 'rate_limited', 'message': 'AI 服务繁忙，请稍后重试', 'retry_after': 40})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'type': 'error', 'message': str(e)})}\n\n"
        finally:
            try:
                current_user_id.reset(token)
            except ValueError:
                pass
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/health")
def health():
    return {"status": "ok"}

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8001))
    host = os.getenv("HOST", "127.0.0.1")
    uvicorn.run("server:app", host=host, port=port, reload=True)
